development:
  adapter: postgresql
  database: ajax_blog_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ajax_blog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ajax_blog_production
  pool: 5
  timeout: 5000