development:
  adapter: postgresql
  database: flatiron_confessional_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: flatiron_confessional_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: flatiron_confessional_production
  pool: 5
  timeout: 5000